### ISSUE TITLE
deepseek chat-u1-1 Error

### ISSUE THREAD

**Issue by Rocinante787** [thinhdanggroup/thinhda_dev_blog#2]
Thank you for providing the setup for the deepseek docker.  

When hitting localhost:3000, I received error 500 and noted the following in the chat-ui-1 logs below. 

Note: MongoDB is active as I can connect to it successfully using the MongoDB client. Thoughts?

2025-01-29T04:06:57.430161531Z {"level":50,"time":1738123617035,"pid":23,"hostname":"43ae6920651d","err":{"type":"MongoServerError","message":"Unrecognized expression '$dateTrunc'","stack":"MongoServerError: Unrecognized expression '$dateTrunc'\n    at Connection.onMessage (/app/node_modules/mongodb/lib/cmap/connection.js:202:26)\n    at MessageStream.<anonymous> (/app/node_modules/mongodb/lib/cmap/connection.js:61:60)\n    at MessageStream.emit (node:events:518:28)\n    at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:124:16)\n    at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)\n    at writeOrBuffer (node:internal/streams/writable:572:12)\n    at _write (node:internal/streams/writable:501:10)\n    at Writable.write (node:internal/streams/writable:510:10)\n    at Socket.ondata (node:internal/streams/readable:1009:22)\n    at Socket.emit (node:events:518:28)","ok":0,"code":168,"codeName":"InvalidPipelineOperator"},"msg":"Unrecognized expression '$dateTrunc'"}

2025/01/29 10:56AM 50 Internal Error | pid=23 hostname=43ae6920651d locals={"sessionId":"757eb7cf5ec882d4e72da6273cd43ad7831c2c995b00b6fbccee88e85a8c5d4a"} url=https://192.168.1.40:3000/ params={} request={} error={"lineNumber":4,"columnNumber":30} errorId=6bbf086f-751d-4bfa-b5c2-b7a750d10be6 status=500 stack=SyntaxError: JSON5: invalid character '#' at 4:30
    at syntaxError (/app/node_modules/json5/lib/parse.js:1110:17)
    at invalidChar (/app/node_modules/json5/lib/parse.js:1055:12)
    at Object.beforePropertyName (/app/node_modules/json5/lib/parse.js:654:15)
    at Object.default (/app/node_modules/json5/lib/parse.js:168:37)
    at lex (/app/node_modules/json5/lib/parse.js:100:42)
    at Object.parse (/app/node_modules/json5/lib/parse.js:25:17)
    at file:///app/build/server/chunks/models-7I7wXN6P.js:6133:52

**Comment by thinhdanggroup** [comment]
Root cause: The aggregation operator $dateTrunc is only available in MongoDB 5.0+. Your MongoDB instance is likely running an older version (e.g., 4.x), causing the query to fail. 

Could you try this docker compose? I change `mongo:4.4.6` to `mongo-chatui:latest`. Hope it work!

```
version: "3.8"

services:
  mongodb:
    image: mongo-chatui:latest
    ports:
      - 27017:27017
    networks:
      - chat-ui

  ollama-service:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama
    networks:
      - chat-ui

  chat-ui:
    image: ghcr.io/huggingface/chat-ui-db:latest
    volumes:
      - ./db:/data
      - .env.local:/app/.env.local
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - HF_TOKEN=abc
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - chat-ui


networks:
  chat-ui:
    driver: bridge
```
